export const API_URL = 'https://restcountries.com/v3.1/all?fields=name,flags,region,subregion,cca3';

export const PREDEFINED_TAGS = {
    "AFG": ["Asia","Southern Asia","white","black"], "ALB": ["Europe","Southeast Europe","red","black"],
    "DZA": ["Africa","Northern Africa","red","white","green","star"], "ARM": ["Asia","Western Asia","red","blue","orange","horizontal","stripes"],
    "AND": ["Europe","Southern Europe","red","blue","yellow","vertical","stripes"], "ARG": ["Americas","South America","red","white","blue","horizontal","stripes"],
    "AUT": ["Europe","Central Europe","red","white","horizontal","stripes"], "AZE": ["Asia","Western Asia","red","white","blue","green","horizontal","stripes","star"],
    "BOL": ["Americas","South America","red","green","yellow","horizontal","stripes"], "BWA": ["Africa","Southern Africa","white","blue","black","horizontal","stripes"],
    "BGR": ["Europe","Southeast Europe","red","white","green","horizontal","stripes"], "COL": ["Americas","South America","red","blue","yellow","horizontal","stripes"],
    "HRV": ["Europe","Southeast Europe","red","white","blue","horizontal","stripes"], "CRI": ["Americas","Central America","red","white","blue","horizontal","stripes"],
    "ECU": ["Americas","South America","red","blue","yellow","horizontal","stripes"], "EGY": ["Africa","Northern Africa","red","white","black","horizontal","stripes"],
    "SLV": ["Americas","Central America","red","white","blue","horizontal","stripes"], "EST": ["Europe","Northern Europe","white","blue","black","horizontal","stripes"],
    "GAB": ["Africa","Middle Africa","blue","green","yellow","horizontal","stripes"], "ETH": ["Africa","Eastern Africa","red","blue","green","yellow","horizontal","stripes","star"],
    "GMB": ["Africa","Western Africa","red","white","blue","green","horizontal","stripes"], "DEU": ["Europe","Western Europe","red","black","horizontal","stripes"],
    "GHA": ["Africa","Western Africa","red","green","black","horizontal","stripes","star"], "HUN": ["Europe","Central Europe","red","white","green","horizontal","stripes"],
    "IND": ["Asia","Southern Asia","red","white","blue","green","horizontal","stripes"], "IRN": ["Asia","Southern Asia","red","white","green","horizontal","stripes"],
    "IRQ": ["Asia","Western Asia","red","white","green","black","horizontal","stripes"], "LVA": ["Europe","Northern Europe","red","white","cross","horizontal","stripes"],
    "LBN": ["Asia","Western Asia","red","white","green","horizontal","stripes"], "LAO": ["Asia","South-Eastern Asia","red","white","blue","horizontal","stripes"],
    "LSO": ["Africa","Southern Africa","red","white","blue","green","black","horizontal","stripes"], "LBY": ["Africa","Northern Africa","red","white","green","black","horizontal","stripes","star"],
    "LTU": ["Europe","Northern Europe","red","green","yellow","horizontal","stripes"], "LUX": ["Europe","Western Europe","red","white","blue","horizontal","stripes"],
    "LBR": ["Africa","Western Africa","red","white","blue","horizontal","stripes","star"], "MWI": ["Africa","Eastern Africa","red","green","black","horizontal","stripes"],
    "MUS": ["Africa","Eastern Africa","red","blue","green","yellow","horizontal","stripes"], "MMR": ["Asia","South-Eastern Asia","red","white","green","yellow","horizontal","stripes","star"],
    "NLD": ["Europe","Western Europe","red","white","blue","horizontal","stripes"], "NIC": ["Americas","Central America","red","white","blue","horizontal","stripes"],
    "NER": ["Africa","Western Africa","red","white","green","orange","horizontal","stripes"], "PRK": ["Asia","Eastern Asia","red","white","blue","horizontal","stripes","star"],
    "PRY": ["Americas","South America","red","white","blue","horizontal","stripes"], "RUS": ["Europe","Eastern Europe","red","white","blue","horizontal","stripes"],
    "RWA": ["Africa","Eastern Africa","blue","green","yellow","horizontal","stripes"], "SLE": ["Africa","Western Africa","white","blue","green","horizontal","stripes"],
    "SVK": ["Europe","Central Europe","red","white","blue","horizontal","stripes"], "SVN": ["Europe","Central Europe","red","white","blue","horizontal","stripes","star"],
    "BHS": ["Americas","Caribbean","yellow","black","horizontal","stripes","left triangle"], "CAF": ["Africa","Middle Africa","red","white","blue","green","yellow","horizontal","stripes","star"],
    "COM": ["Africa","Eastern Africa","red","white","blue","green","yellow","horizontal","stripes","left triangle"], "CUB": ["Americas","Caribbean","red","white","blue","horizontal","stripes","left triangle","star"],
    "GNQ": ["Africa","Middle Africa","red","white","blue","green","horizontal","stripes","left triangle"], "GRC": ["Europe","Southern Europe","white","blue","cross","horizontal","stripes"],
    "HND": ["Americas","Central America","white","horizontal","stripes","star"], "JOR": ["Asia","Western Asia","red","white","green","black","horizontal","stripes","left triangle","star"],
    "KEN": ["Africa","Eastern Africa","red","white","green","black","horizontal","stripes"], "KWT": ["Asia","Western Asia","red","white","green","black","horizontal","stripes"],
    "MYS": ["Asia","South-Eastern Asia","red","white","blue","yellow","horizontal","stripes","star"], "MOZ": ["Africa","Eastern Africa","red","white","yellow","black","horizontal","stripes","left triangle","star"],
    "STP": ["Africa","Middle Africa","red","white","blue","green","yellow","black","horizontal","stripes","star"], "SRB": ["Europe","Southeast Europe","red","white","blue","horizontal","stripes"],
    "SSD": ["Africa","Middle Africa","red","white","blue","green","yellow","black","horizontal","stripes","left triangle","star"], "ESP": ["Europe","Southern Europe","red","yellow","horizontal","stripes"],
    "SDN": ["Africa","Northern Africa","red","white","green","black","horizontal","stripes"], "SUR": ["Americas","South America","red","white","green","yellow","horizontal","stripes","star"],
    "SYR": ["Asia","Western Asia","red","white","green","black","horizontal","stripes","star"], "TJK": ["Asia","Central Asia","red","white","green","yellow","horizontal","stripes","star"],
    "THA": ["Asia","South-Eastern Asia","red","white","blue","horizontal","stripes"], "TGO": ["Africa","Western Africa","red","white","green","yellow","horizontal","stripes","star"],
    "UGA": ["Africa","Eastern Africa","red","white","yellow","black","horizontal","stripes"], "ARE": ["Asia","Western Asia","red","white","green","black","horizontal","stripes"],
    "USA": ["Americas","North America","red","white","blue","horizontal","stripes","star"], "URY": ["Americas","South America","white","blue","yellow","horizontal","stripes"],
    "UZB": ["Asia","Central Asia","red","white","green","horizontal","stripes","star"], "VEN": ["Americas","South America","red","white","blue","yellow","horizontal","stripes","star"],
    "YEM": ["Asia","Western Asia","red","white","black","horizontal","stripes"], "ZWE": ["Africa","Southern Africa","red","white","green","yellow","black","horizontal","stripes","left triangle","star"],
    "BRB": ["Americas","Caribbean","red","black","vertical","stripes"], "BEL": ["Europe","Western Europe","red","yellow","black","vertical","stripes"],
    "CMR": ["Africa","Middle Africa","red","green","yellow","vertical","stripes","star"], "KHM": ["Asia","South-Eastern Asia","red","white","blue","horizontal","stripes"],
    "TCD": ["Africa","Middle Africa","red","blue","vertical","stripes"], "FRA": ["Europe","Western Europe","red","white","blue","vertical","stripes"],
    "GTM": ["Americas","Central America","red","white","blue","vertical","stripes"], "GIN": ["Africa","Western Africa","red","green","yellow","vertical","stripes"],
    "IRL": ["Europe","Northern Europe","white","green","orange","vertical","stripes"], "ITA": ["Europe","Southern Europe","red","white","green","vertical","stripes"],
    "CIV": ["Africa","Western Africa","white","green","orange","vertical","stripes"], "MLI": ["Africa","Western Africa","red","green","yellow","vertical","stripes"],
    "MEX": ["Americas","North America","red","white","green","vertical","stripes"], "MDA": ["Europe","Eastern Europe","red","blue","yellow","vertical","stripes"],
    "MNG": ["Asia","Eastern Asia","red","blue","vertical","stripes"], "NGA": ["Africa","Western Africa","white","green","vertical","stripes"],
    "PER": ["Americas","South America","red","white","vertical","stripes"], "ROU": ["Europe","Southeast Europe","red","blue","yellow","vertical","stripes"],
    "SEN": ["Africa","Western Africa","red","green","yellow","vertical","stripes","star"], "CZE": ["Europe","Central Europe","red","white","blue","left triangle"],
    "DJI": ["Africa","Eastern Africa","red","white","blue","green","left triangle","star"], "GUY": ["Americas","South America","red","white","green","yellow","black","left triangle"],
    "PHL": ["Asia","South-Eastern Asia","red","white","blue","yellow","left triangle","star"], "ZAF": ["Africa","Southern Africa","red","white","blue","green","yellow","black","left triangle"],
    "TLS": ["Asia","South-Eastern Asia","red","white","yellow","black","left triangle","star"], "VUT": ["Oceania","Melanesia","red","green","yellow","black","left triangle"],
    "AGO": ["Africa","Middle Africa","red","yellow","black","star"], "BDI": ["Africa","Eastern Africa","red","white","green","diagonal"],
    "BRN": ["Asia","South-Eastern Asia","red","white","yellow","black","diagonal"], "COD": ["Africa","Middle Africa","red","blue","yellow","diagonal","star"],
    "JAM": ["Americas","Caribbean","green","black","diagonal"], "MHL": ["Oceania","Micronesia","white","blue","orange","diagonal","star"],
    "NAM": ["Africa","Southern Africa","red","white","blue","green","diagonal"], "COG": ["Africa","Middle Africa","red","green","yellow","diagonal"],
    "KNA": ["Americas","Caribbean","red","white","green","yellow","black","diagonal","star"], "SYC": ["Africa","Eastern Africa","red","white","blue","green","yellow","diagonal"],
    "SLB": ["Oceania","Melanesia","white","blue","green","yellow","diagonal","star"], "TZA": ["Africa","Eastern Africa","blue","green","yellow","black","diagonal"],
    "TTO": ["Americas","Caribbean","red","white","black","diagonal"], "TUV": ["Oceania","Polynesia","blue","yellow","cross","star"],
    "VNM": ["Asia","South-Eastern Asia","red","yellow","star"], "TKM": ["Asia","Central Asia","red","white","green","star"],
    "TUR": ["Asia","Western Asia","red","white","star"], "TUN": ["Africa","Northern Africa","red","white","star"],
    "SOM": ["Africa","Eastern Africa","red","white","blue","star"], "SGP": ["Asia","South-Eastern Asia","red","white","star"],
    "WSM": ["Oceania","Polynesia","red","white","blue","star"], "PAN": ["Americas","Central America","red","white","blue","star"],
    "PNG": ["Oceania","Melanesia","red","white","black","star"], "PAK": ["Asia","Southern Asia","red","white","green","star"],
    "NZL": ["Oceania","red","white","blue","cross","star"], "MAR": ["Africa","Northern Africa","red","green","star"],
    "NRU": ["Oceania","Micronesia","white","blue","yellow","star"], "FSM": ["Oceania","Micronesia","white","blue","star"],
    "MRT": ["Africa","Western Africa","red","green","yellow","star"], "GNB": ["Africa","Western Africa","red","green","yellow","black","star"],
    "GRD": ["Americas","Caribbean","red","green","yellow","star"], "DMA": ["Americas","Caribbean","red","white","green","yellow","black","cross","star"],
    "CHN": ["Asia","Eastern Asia","red","yellow","star"], "CHL": ["Americas","South America","red","white","blue","star"],
    "CPV": ["Africa","Western Africa","red","white","blue","yellow","star"], "BFA": ["Africa","Western Africa","red","green","yellow","star"],
    "BRA": ["Americas","South America","white","blue","green","yellow","star"], "BIH": ["Europe","Southeast Europe","white","blue","yellow","star"],
    "AUS": ["Oceania","white","blue","cross","star"], "CYP": ["Europe","Southern Europe","red","white","green"],
    "VAT": ["Europe","Southern Europe","red","white","yellow"]
};

export const COMMON_COLORS = ['red', 'white', 'blue', 'green', 'yellow', 'black', 'orange'];
